### ISSUE TITLE
Izin Fork

### ISSUE THREAD

**Issue by ghost** [adrik27/UndanganSyukuran-IzzaIzzun.github.io#1]
Salam...

Maaf mengganggu,
Saya meminta izin menggunakan repo ini untuk acara undangan kami sendiri, apakah diizinkan?

Terima kasih

**Comment by adrik27** [comment]
Iya monggo silahkan, tetapi masih ada kekurangan, silahkan jenengan
sesuaikan kebutuhan

Pada tanggal Sen, 27 Feb 2023 10.22, Ahla Mahfudz ***@***.***>
menulis:

**Comment by ghost** [comment]
suwun
